services:
  - type: web
    name: file-forge
    env: docker
    plan: starter # Recommend starter plan because PaddleOCR needs > 512MB RAM
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FILE_FORGE_API_KEY
        generateValue: true
      - key: PORT
        value: 8000
